# Generated by Django 5.2.5 on 2025-08-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_name',
            field=models.CharField(default='My Investment Portfolio', help_text='Name of the portfolio this transaction belongs to', max_length=100),
        ),
    ]
