# Generated by Django 5.2.5 on 2025-08-25 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_add_login_attempt_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='stocks_logi_usernam_f42e9a_idx',
            old_name='stocks_logi_usernam_2b0dca_idx',
        ),
        migrations.RenameIndex(
            model_name='loginattempt',
            new_name='stocks_logi_ip_addr_26057c_idx',
            old_name='stocks_logi_ip_addr_4e2e5d_idx',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(default=1, help_text='Owner of this portfolio transaction', on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
