# Generated by Django 5.2.5 on 2025-08-28 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_rename_stocks_logi_usernam_2b0dca_idx_stocks_logi_usernam_f42e9a_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Brief subject line for the support message', max_length=200)),
                ('message', models.TextField(help_text='Detailed description of the issue or question')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', help_text='Priority level of the support request', max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', help_text='Current status of the support request', max_length=15)),
                ('admin_response', models.TextField(blank=True, help_text="Admin's response to the support message")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the support request was resolved', null=True)),
                ('admin_responder', models.ForeignKey(blank=True, help_text='Admin who responded to this message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(help_text='User who submitted the support message', on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='stocks_supp_user_id_fc6a15_idx'), models.Index(fields=['status', '-created_at'], name='stocks_supp_status_e0db39_idx'), models.Index(fields=['priority', '-created_at'], name='stocks_supp_priorit_f00a19_idx')],
            },
        ),
    ]
