# Generated by Django 5.2.5 on 2025-09-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_add_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_portfolio',
            field=models.CharField(default='My Investment Portfolio', help_text='Currently selected portfolio name for this user', max_length=100),
        ),
    ]
